grpc: https://grpc.us.shyft.to
# Test the code, monitor behavior, and simulate transactions without risking funds.
read_only: false
# Retry sending orders until they are confirmed. Not recommended since orders can be out of date if the market moves.
retry_until_confirmed: false
# Bracket orders are placed at these percentages of the spread.
pct_spread_brackets: [ 33, 66, 100 ]
# Use the real on-chain spread unless it is greater than this percentage.
pct_max_spread: 0.12
# Use the real on-chain spread unless it is less than this percentage.
pct_min_spread: 0.06
# Stop loss to exit position if below entry by this percentage.
pct_exit_deviation: 0.06
leverage: 4