grpc: https://grpc.us.shyft.to
# Test the code, monitor behavior, and simulate transactions without risking funds.
read_only: false
# Retry sending orders until they are confirmed. Not recommended since orders can be out of date if the market moves.
retry_until_confirmed: false
# Stop loss to exit position if below entry by this percentage.
pct_exit_deviation: 0.05
leverage: 1